// End-to-end tests of the built engine under plain Node, through the same loader and marshalling
// code the worker host uses in a browser (host/src/worker.ts). Skipped until the engine is built
// (npm run test:engine fails instead).
//
//   node --test test/engine.test.ts                           # dist/engine-st.mjs
//   ENGINE_VARIANT=mt node --test test/engine.test.ts
//   ENGINE_DIR=$ORCA_WASM_ROOT/build-st/out node --test test/engine.test.ts
//
// Besides "does it slice", every G-code the engine returns is read back with a footer parser
// (test/helpers/gcodeStats.ts) and a G-code toolpath parser (test/helpers/parseGcode.ts): the stats
// must be identical, and the toolpaths the engine builds from Orca's GCodeProcessor must match what
// the parser draws from the text. The G-code is written to ENGINE_TEST_OUT for inspection.
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { before, describe, test, type TestContext } from 'node:test';
import { readConfigDefinitions } from '../host/src/configDefinitions.ts';
import { EngineJobError, runCheck, runSlice, type OrcaEngineModule } from '../host/src/worker.ts';
import type { CheckOutput, EngineObject, EngineWarning, GcodeStats, ParsedGcode, SliceOutput } from '../packages/protocol/src/v1.ts';
import { parseStatsText } from './helpers/gcodeStats.ts';
import { parseGcode, sizeCode } from './helpers/parseGcode.ts';
import {
  benchy,
  benchyAvailable,
  benchyPath,
  bounds,
  checkJob,
  cube,
  cylinder,
  engineSkip,
  flatPresets,
  m1Presets,
  ms,
  objectSettingsPlate,
  outDir,
  sliceJob,
  startEngine,
  translate,
  variant,
  X1C,
  type Presets,
} from './fixtures.ts';

if (engineSkip) console.log(`# ${engineSkip}`);
// 3DBenchy is not part of the repository: the Benchy tests are skipped rather than failed without it.
const needsBenchy = benchyAvailable ? {} : { skip: `${benchyPath} not found (set ENGINE_TEST_BENCHY)` };

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface Sliced {
  output: SliceOutput;
  progress: Array<[number, string]>;
  warnings: EngineWarning[];
  wallMs: number;
}

function slice(engine: OrcaEngineModule, presets: Presets, objects: EngineObject[]): Sliced {
  const progress: Array<[number, string]> = [];
  const warnings: EngineWarning[] = [];
  const started = performance.now();
  const output = runSlice(engine, sliceJob(presets, objects), (p, m) => progress.push([p, m]), (w) => warnings.push(w));
  return { output, progress, warnings, wallMs: performance.now() - started };
}

/** The EngineError a job fails with (fails the test if it succeeds or the engine itself breaks). */
function failure(run: () => unknown) {
  try {
    run();
  } catch (err) {
    if (err instanceof EngineJobError) return err.error;
    throw err;
  }
  assert.fail('expected the job to fail');
}

/** The stats the G-code text itself gives: its header and footer. */
function statsFromText(gcode: Uint8Array): GcodeStats {
  const decoder = new TextDecoder();
  const head = decoder.decode(gcode.subarray(0, 16 * 1024));
  const tail = decoder.decode(gcode.subarray(Math.max(0, gcode.length - 512 * 1024)));
  return parseStatsText(head, tail);
}

function saveGcode(name: string, gcode: Uint8Array): string {
  const dir = path.join(outDir, `engine-${variant}`);
  mkdirSync(dir, { recursive: true });
  const file = path.join(dir, name);
  writeFileSync(file, gcode);
  return file;
}

/** The G-code without the lines that legitimately differ between runs. */
function stableText(gcode: Uint8Array): string {
  return new TextDecoder()
    .decode(gcode)
    .split('\n')
    .filter((line) => !line.startsWith('; generated by '))
    .join('\n');
}

interface ObjectLayers {
  /** Print Zs the object extrudes at, ascending. */
  zs: number[];
  /** Per feature type (";TYPE:") on the layer at Z = 10: mm of filament and mm of path extruded. */
  at10: Map<string, { e: number; length: number }>;
}

/**
 * Per object (Klipper's EXCLUDE_OBJECT_START/END blocks, named "<object>_id_<n>_copy_<n>"): where
 * it prints and what each feature extrudes at Z = 10, as the CLI experiment measured it
 * (a prototype script, cli3mf/run.mjs). The M1 presets use relative extrusion (M83) and no arcs.
 */
function perObjectLayers(gcode: Uint8Array): Map<string, ObjectLayers> {
  const text = new TextDecoder().decode(gcode);
  assert.match(text, /^M83\b/m, 'relative extrusion');
  const zs = new Map<string, Set<number>>();
  const at10 = new Map<string, ObjectLayers['at10']>();
  const AXIS = { X: / X(-?[\d.]+)/, Y: / Y(-?[\d.]+)/, E: / E(-?[\d.]+)/ };
  const axis = (line: string, letter: keyof typeof AXIS) => AXIS[letter].exec(line)?.[1];
  let [x, y, z] = [0, 0, 0];
  let current: string | null = null;
  let type = '';
  for (const line of text.split('\n')) {
    if (line.startsWith(';Z:')) z = Number(line.slice(3));
    else if (line.startsWith('EXCLUDE_OBJECT_START NAME=')) {
      current = line.slice('EXCLUDE_OBJECT_START NAME='.length).trim().replace(/_id_\d+_copy_\d+$/, '');
      if (!zs.has(current)) {
        zs.set(current, new Set());
        at10.set(current, new Map());
      }
    } else if (line.startsWith('EXCLUDE_OBJECT_END')) current = null;
    else if (line.startsWith(';TYPE:')) type = line.slice(6).trim();
    else if (/^G[0-3] /.test(line)) {
      assert.ok(!/^G[23] /.test(line), 'no arcs');
      const nx = Number(axis(line, 'X') ?? x);
      const ny = Number(axis(line, 'Y') ?? y);
      const e = Number(axis(line, 'E') ?? 0);
      if (current !== null && e > 0) {
        zs.get(current)!.add(z);
        if (Math.abs(z - 10) < 1e-6) {
          const byType = at10.get(current)!;
          const feature = byType.get(type) ?? { e: 0, length: 0 };
          feature.e += e;
          feature.length += Math.hypot(nx - x, ny - y);
          byType.set(type, feature);
        }
      }
      [x, y] = [nx, ny];
    }
  }
  const out = new Map<string, ObjectLayers>();
  for (const [name, set] of zs) out.set(name, { zs: [...set].sort((a, b) => a - b), at10: at10.get(name)! });
  return out;
}

/** first, first + step, … up to `last`, rounded like Orca's ";Z:" lines. */
function zSteps(first: number, step: number, last: number): number[] {
  const out: number[] = [];
  for (let i = 0; first + i * step <= last + 1e-9; i++) out.push(Math.round((first + i * step) * 1000) / 1000);
  return out;
}

function report(t: TestContext, label: string, { output, wallMs }: Sliced): void {
  const { stats, timings, toolpaths } = output;
  t.diagnostic(
    `${label}: ${ms(wallMs)} (load ${ms(timings.load)}, slice ${ms(timings.slice)}, export ${ms(timings.export)}); ` +
      `${(output.gcode.length / 1e6).toFixed(2)} MB G-code; ${stats.layers} layers, ${stats.printTimeText}, ` +
      `${stats.filamentMm} mm / ${stats.filamentG} g filament, max Z ${stats.maxZ}` +
      (toolpaths ? `; ${toolpaths.extrusions.count.toLocaleString('en')} extrusion + ${toolpaths.travels.count.toLocaleString('en')} travel segments` : ''),
  );
}

/** Progress must be monotonic, within 0-100, and end near the top. */
function assertProgress(progress: Array<[number, string]>): void {
  assert.ok(progress.length > 3, 'progress was reported');
  for (let i = 1; i < progress.length; i++) assert.ok(progress[i][0] >= progress[i - 1][0], `progress went back at ${JSON.stringify(progress[i])}`);
  assert.ok(progress.every(([p]) => p >= 0 && p <= 100));
  assert.ok(progress.at(-1)![0] >= 95, `last progress ${JSON.stringify(progress.at(-1))}`);
}

/** Stats must mean exactly what the G-code header and footer say. */
function assertStatsMatchText(output: SliceOutput): void {
  assert.deepEqual(output.stats, statsFromText(output.gcode), 'stats differ from the G-code header/footer');
  const s = output.stats;
  assert.ok(s.printTimeSeconds! > 0 && s.filamentMm! > 0 && s.filamentG! > 0 && s.layers! > 0 && s.maxZ! > 0, JSON.stringify(s));
}

/**
 * The engine's toolpaths (from Orca's GCodeProcessor) against the UI parser's reading of the same
 * G-code text: same layers and roles, near-identical lengths and segment counts.
 */
function assertToolpathsMatchParser(t: TestContext, output: SliceOutput): void {
  const engine = output.toolpaths;
  assert.ok(engine, 'toolpaths were requested');
  const parsed = parseGcode(output.gcode);

  assert.equal(engine.layerCount, parsed.layerCount, 'layer count');
  assert.equal(engine.layerZ.length, engine.layerCount);
  assert.equal(engine.extrusions.layerStart.length, engine.layerCount + 1);
  assert.equal(engine.extrusions.layerStart[engine.layerCount], engine.extrusions.count);
  assert.equal(engine.travels.layerStart[engine.layerCount], engine.travels.count);
  assert.equal(engine.extrusions.positions.length, engine.extrusions.count * 6);
  assert.equal(engine.extrusions.roleIndex.length, engine.extrusions.count);
  assert.equal(engine.extrusions.width.length, engine.extrusions.count);
  assert.equal(engine.extrusions.height.length, engine.extrusions.count);
  for (let l = 1; l <= engine.layerCount; l++) assert.ok(engine.extrusions.layerStart[l] >= engine.extrusions.layerStart[l - 1]);
  for (const array of Object.values(output.toolpathExtras!)) assert.equal((array as ArrayLike<number>).length, engine.extrusions.count);

  assert.deepEqual([...engine.roles].sort(), [...parsed.roles].sort(), 'roles');
  for (const [i, role] of engine.roles.entries()) {
    const theirs = parsed.roleLength[parsed.roles.indexOf(role)];
    const ours = engine.roleLength[i];
    assert.ok(Math.abs(ours - theirs) <= Math.max(1, theirs * 0.02), `${role}: ${ours.toFixed(1)} mm vs parser ${theirs.toFixed(1)} mm`);
  }

  let sameZ = 0;
  for (let l = 0; l < engine.layerCount; l++) if (Math.abs(engine.layerZ[l] - parsed.layerZ[l]) < 2e-3) sameZ++;
  assert.ok(sameZ >= engine.layerCount * 0.95, `layer Z agrees on ${sameZ}/${engine.layerCount} layers`);

  const ratio = engine.extrusions.count / parsed.extrusions.count;
  t.diagnostic(
    `segments: engine ${engine.extrusions.count} extrusions / ${engine.travels.count} travels, ` +
      `parser ${parsed.extrusions.count} / ${parsed.travels.count}; line width ${engine.lineWidth} vs ${parsed.lineWidth}`,
  );
  // One segment per G-code move on both sides (arcs, off in the M1 presets, would differ a little:
  // Orca and the parser tessellate them differently).
  assert.ok(Math.abs(ratio - 1) < 0.005, `extrusion segments: engine ${engine.extrusions.count}, parser ${parsed.extrusions.count}`);
  assert.equal(engine.lineWidth, parsed.lineWidth, 'dominant line width');
  assertBeadsMatchParser(t, engine, parsed);
  // The engine's height codes are the processor's own heights (toolpathExtras.height, in mm).
  const heights = output.toolpathExtras!.height;
  for (let s = 0; s < engine.extrusions.count; s++) {
    if (engine.extrusions.height[s] !== sizeCode(heights[s])) assert.fail(`segment ${s}: height code ${engine.extrusions.height[s]} for ${heights[s]} mm`);
  }
  assert.ok(engine.bounds && parsed.bounds);
  for (let a = 0; a < 2; a++) {
    assert.ok(Math.abs(engine.bounds.min[a] - parsed.bounds.min[a]) < 0.05, `bounds.min[${a}]`);
    assert.ok(Math.abs(engine.bounds.max[a] - parsed.bounds.max[a]) < 0.05, `bounds.max[${a}]`);
  }
}

/**
 * Every bead as wide and as tall as Orca draws it: the width and height GCodeProcessor gave each
 * move (the engine's toolpaths) against what the parser works out from the text, segment by
 * segment, within one size code (0.01 mm; float against double rounding).
 */
function assertBeadsMatchParser(t: TestContext, engine: ParsedGcode, parsed: ParsedGcode): void {
  const ours = engine.extrusions, theirs = parsed.extrusions;
  let compared = 0;
  const off: string[] = [];
  for (let l = 0; l < engine.layerCount; l++) {
    const first = ours.layerStart[l], firstParsed = theirs.layerStart[l];
    const count = ours.layerStart[l + 1] - first;
    // Where a layer has as many segments on both sides, they are the same moves in the same order.
    if (count !== theirs.layerStart[l + 1] - firstParsed) continue;
    for (let k = 0; k < count; k++) {
      const s = first + k, p = firstParsed + k;
      const sameEnd = Math.abs(ours.positions[s * 6 + 3] - theirs.positions[p * 6 + 3]) < 1e-3 && Math.abs(ours.positions[s * 6 + 4] - theirs.positions[p * 6 + 4]) < 1e-3;
      if (!sameEnd) continue;
      compared++;
      if (Math.abs(ours.width[s] - theirs.width[p]) > 1 || Math.abs(ours.height[s] - theirs.height[p]) > 1) {
        off.push(`layer ${l} ${engine.roles[ours.roleIndex[s]]}: width ${ours.width[s]}/${theirs.width[p]}, height ${ours.height[s]}/${theirs.height[p]}`);
      }
    }
  }
  t.diagnostic(`bead widths and heights compared on ${compared} of ${ours.count} segments, ${off.length} differ`);
  assert.ok(compared >= ours.count * 0.95, `only ${compared} of ${ours.count} segments line up with the parser's`);
  assert.deepEqual(off.slice(0, 10), [], `${off.length} segments differ (engine/parser, size codes)`);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe(`engine-${variant}`, { skip: engineSkip }, () => {
  let engine: OrcaEngineModule;
  let presets: Presets;

  before(async () => {
    const started = await startEngine();
    engine = started.engine;
    presets = await m1Presets();
    console.log(`# engine-${variant} ready in ${ms(started.initMs)}: OrcaSlicer ${engine.version().orcaVersion} (${engine.version().orcaCommit})`);
  });

  test('reports its Orca version', () => {
    const version = engine.version();
    assert.match(version.orcaVersion, /^\d+\.\d+\.\d+/);
    assert.equal(typeof version.orcaCommit, 'string');
  });

  test('slices a 20 mm cube at [100, 90]', (t) => {
    const sliced = slice(engine, presets, [{ name: 'Cube.stl', positions: cube([100, 90]) }]);
    const { output } = sliced;
    report(t, 'cube', sliced);
    t.diagnostic(`G-code: ${saveGcode('cube.gcode', output.gcode)}`);

    const text = new TextDecoder().decode(output.gcode);
    assert.match(text, /^; generated by OrcaSlicer 2\.5\.0-dev/m);
    assert.match(text, /EXCLUDE_OBJECT_DEFINE NAME=Cube\.stl/, 'object named as Orca\'s CLI names it');
    assert.equal(output.stats.maxZ, 20);
    assert.ok(Math.abs(output.stats.layers! - 100) <= 1, `layers ${output.stats.layers}`);
    assertProgress(sliced.progress);
    assertStatsMatchText(output);
    assertToolpathsMatchParser(t, output);
    assert.deepEqual(output.warnings, sliced.warnings, 'every warning was also streamed');
  });

  test('slicing the same plate again gives the same G-code (a fresh Print per job)', () => {
    const objects = [{ name: 'Cube.stl', positions: cube([100, 90]) }];
    const first = slice(engine, presets, objects).output;
    const second = slice(engine, presets, objects).output;
    assert.equal(stableText(second.gcode), stableText(first.gcode));
  });

  test('slices Benchy at [100, 90]', needsBenchy, async (t) => {
    const positions = await benchy([100, 90]);
    const size = bounds(positions);
    const sliced = slice(engine, presets, [{ name: 'Benchy.stl', positions }]);
    const { output } = sliced;
    report(t, 'benchy', sliced);
    t.diagnostic(`G-code: ${saveGcode('benchy.gcode', output.gcode)}`);

    const height = size.max[2] - size.min[2];
    assert.ok(Math.abs(output.stats.maxZ! - height) < 0.25, `max Z ${output.stats.maxZ} for a ${height.toFixed(2)} mm model`);
    assert.ok(Math.abs(output.stats.layers! - height / 0.2) <= 2, `layers ${output.stats.layers}`);
    assert.ok(output.stats.printTimeSeconds! > 600, 'a Benchy takes more than 10 minutes');
    assertProgress(sliced.progress);
    assertStatsMatchText(output);
    assertToolpathsMatchParser(t, output);
  });

  test('support, ironing, gap fill and combined infill: every bead as wide and as tall as Orca draws it', needsBenchy, async (t) => {
    const positions = await benchy([100, 90]);
    const process = {
      ...presets.process,
      enable_support: '1',
      support_type: 'normal(auto)',
      ironing_type: 'top',
      wall_generator: 'classic',
      gap_fill_target: 'everywhere',
      infill_combination: '1',
    };
    const sliced = slice(engine, { ...presets, process }, [{ name: 'Benchy.stl', positions }]);
    const { output } = sliced;
    report(t, 'benchy with support and ironing', sliced);
    assertToolpathsMatchParser(t, output);

    // Heights that are not the layer's: GCodeProcessor's, as Orca's preview draws them.
    const { roles, extrusions } = output.toolpaths!;
    const heightsOf = (role: string) => {
      const index = roles.indexOf(role);
      assert.ok(index >= 0, `no ${role}`);
      return new Set(extrusions.height.filter((_, s) => extrusions.roleIndex[s] === index));
    };
    assert.deepEqual(heightsOf('Custom'), new Set([15]), 'the purge line, 0.15 mm above the bed');
    assert.deepEqual(heightsOf('Bridge'), new Set([40]), 'bridges, as tall as the nozzle is wide');
    assert.ok(heightsOf('Sparse infill').has(40), 'infill combined over two layers');
    assert.deepEqual(heightsOf('Ironing'), new Set([1]), 'ironing, a film');
    assert.ok(heightsOf('Support').size > 3, 'support layers of their own heights');
    assert.ok(heightsOf('Gap infill').size > 0);
  });

  test('a cube in the M1 front notch fails with -64 (exclusion volume)', () => {
    const error = failure(() => slice(engine, presets, [{ name: 'Notch.stl', positions: cube([100, 14]) }]));
    assert.equal(error.code, -64, error.message);
    assert.match(error.message, /exclusion volume/i);
    assert.deepEqual(error.objects, ['Notch.stl']);
  });

  test('cubes beside the notch slice, and the skirt crossing it is only a warning', (t) => {
    const sliced = slice(engine, presets, [
      { name: 'Left.stl', positions: cube([40, 15]) },
      { name: 'Right.stl', positions: cube([160, 15]) },
    ]);
    report(t, 'notch neighbours', sliced);
    const kinds = sliced.output.warnings.map((w) => `${w.kind}: ${w.message}`);
    t.diagnostic(`warnings: ${kinds.length ? kinds.join(' | ') : 'none'}`);
    // WASM_ENGINE_SPEC.md §7 expects the fork's path check to flag the skirt; whether it does depends on the
    // branch's skirt/travel handling, so this is reported rather than asserted.
  });

  test('an object partly off the bed fails with -52', () => {
    const error = failure(() =>
      slice(engine, presets, [
        { name: 'Cube.stl', positions: cube([100, 90]) },
        { name: 'Edge.stl', positions: cube([195, 90]) },
      ]),
    );
    assert.equal(error.code, -52, error.message);
    assert.deepEqual(error.objects, ['Edge.stl']);
  });

  test('a plate with nothing fully on the bed fails with -50', () => {
    // As in the CLI, "nothing inside" is checked first, so a lone object over the edge is -50 too.
    for (const center of [
      [400, 400],
      [195, 90],
    ] as Array<[number, number]>) {
      const error = failure(() => slice(engine, presets, [{ name: 'Far.stl', positions: cube(center) }]));
      assert.equal(error.code, -50, error.message);
    }
  });

  test('an unflattened preset fails with -5', () => {
    const unflattened = { ...presets, process: { ...presets.process, inherits: 'fdm_process_muon_m1_common' } };
    const error = failure(() => slice(engine, unflattened, [{ name: 'Cube.stl', positions: cube([100, 90]) }]));
    assert.equal(error.code, -5, error.message);
    assert.match(error.message, /inherits/);
  });

  test('an empty mesh fails with -6 and the engine carries on', () => {
    const error = failure(() => slice(engine, presets, [{ name: 'Empty.stl', positions: new Float32Array(0) }]));
    assert.equal(error.code, -6, error.message);
    slice(engine, presets, [{ name: 'Cube.stl', positions: cube([100, 90]) }]);
  });

  test('a mesh without one usable triangle fails with -6 and says so', () => {
    for (const [name, positions] of [
      ['Point.stl', new Float32Array(90).fill(5)], // every vertex the same point: zero area
      ['NaN.stl', new Float32Array(108).fill(NaN)],
    ] as Array<[string, Float32Array]>) {
      const error = failure(() => slice(engine, presets, [{ name, positions }]));
      assert.equal(error.code, -6, error.message);
      assert.match(error.message, /has no usable triangles/);
      assert.deepEqual(error.objects, [name]);
    }
  });

  test('a preset value Orca cannot read fails with -5 naming the key, not a key it then lost', () => {
    // Orca's load_from_json stops reading the file at an array it cannot parse, and skips numbers.
    const cases: Array<[string, (p: Presets) => void, string]> = [
      ['process', (p) => (p.process.top_surface_acceleration = [null] as unknown as string[]), 'top_surface_acceleration'],
      ['machine', (p) => (p.machine.nozzle_diameter = ['0.4', 3] as unknown as string[]), 'nozzle_diameter'],
      ['filament', (p) => (p.filaments[0].during_print_exhaust_fan_speed = [null] as unknown as string[]), 'during_print_exhaust_fan_speed'],
      ['process', (p) => (p.process.layer_height = 0.2 as unknown as string), 'layer_height'],
    ];
    for (const [type, mutate, key] of cases) {
      const broken = structuredClone(presets);
      mutate(broken);
      const error = failure(() => slice(engine, broken, [{ name: 'Cube.stl', positions: cube([100, 90]) }]));
      assert.equal(error.code, -5, error.message);
      assert.ok(error.message.startsWith(`The ${type} preset "`) && error.message.includes(`"${key}"`), error.message);
    }
    // A value Orca itself rejects: its text, without the exception type load_from_json puts first.
    const notANumber = structuredClone(presets);
    notANumber.process.layer_height = 'abc';
    const error = failure(() => slice(engine, notANumber, [{ name: 'Cube.stl', positions: cube([100, 90]) }]));
    assert.equal(error.code, -5, error.message);
    assert.equal(error.message, 'The process preset could not be parsed: Invalid value provided for parameter layer_height: abc');
  });

  test('a setting that is not a finite number fails with -100 and names the setting', () => {
    // "1e400" loads as infinity; Orca only fails when it writes the G-code's config block, like the CLI.
    const broken = structuredClone(presets);
    broken.filaments[0].filament_retraction_length = ['1e400'];
    const error = failure(() => slice(engine, broken, [{ name: 'Cube.stl', positions: cube([100, 90]) }]));
    assert.equal(error.code, -100, error.message);
    assert.match(error.message, /"filament_retraction_length"/);
  });

  test('Bambu Lab G-code is the same in every job: label ids 1..n, object ids from 0', async () => {
    const x1c = await flatPresets(X1C);
    const plate = [
      { name: 'Cube.stl', positions: cube([100, 90], 15) },
      { name: 'Cube_2.stl', positions: cube([140, 90], 15) },
    ];
    const first = slice(engine, x1c, plate).output;
    // Any job in between moves Orca's process-wide object ids on.
    slice(engine, presets, [{ name: 'Cube.stl', positions: cube([100, 90]) }]);
    const second = slice(engine, x1c, plate).output;

    const text = new TextDecoder().decode(first.gcode);
    assert.match(text, /^; model label id: 1,2$/m);
    assert.match(text, /^; start printing object, unique label id: 2$/m);
    assert.match(text, /^; printing object Cube\.stl id:0 copy 0$/m);
    assert.match(text, /^; printing object Cube_2\.stl id:1 copy 0$/m);
    assert.equal(stableText(second.gcode), stableText(first.gcode));
  });

  test('arc fitting turns walls into G2/G3 when the overhang fan does not need them point by point', (t) => {
    const walls = (overhangFan: '0' | '1') => {
      const arcs = structuredClone(presets);
      arcs.process.enable_arc_fitting = '1';
      arcs.filaments[0].enable_overhang_bridge_fan = [overhangFan];
      const { output } = slice(engine, arcs, [{ name: 'Cylinder.stl', positions: cylinder([100, 90], 15, 10) }]);
      assertStatsMatchText(output);
      let role = '';
      let moves = 0;
      let arcMoves = 0;
      for (const line of new TextDecoder().decode(output.gcode).split('\n')) {
        if (line.startsWith(';TYPE:')) role = line.slice(6);
        else if (/wall/i.test(role) && /^G[123] .*E/.test(line)) {
          moves++;
          if (line[1] !== '1') arcMoves++;
        }
      }
      return { moves, arcMoves };
    };
    const plain = walls('0');
    assert.ok(plain.arcMoves > plain.moves / 4, `${plain.arcMoves} of ${plain.moves} wall moves are arcs`);
    // Orca since 68ce4da19f / e8115658e0 writes every wall point by point while the overhang fan is
    // on, so arc fitting then stops at the walls (engine/PATCHES.md); reported, not asserted.
    const fan = walls('1');
    t.diagnostic(`wall arcs: ${plain.arcMoves}/${plain.moves} moves with the overhang fan off, ${fan.arcMoves}/${fan.moves} with it on`);
  });

  test('placement check: inside, over the edge, and in the notch', (t) => {
    const objects = [
      { name: 'Centre.stl', positions: cube([100, 90]) },
      { name: 'Edge.stl', positions: cube([195, 90]) },
      { name: 'Notch.stl', positions: cube([100, 14]) },
    ];
    let started = performance.now();
    const first: CheckOutput = runCheck(engine, checkJob(presets, objects));
    const firstMs = performance.now() - started;

    assert.deepEqual(
      first.objects.map((o) => [o.name, o.inside, o.exclusionHits.length > 0]),
      [
        ['Centre.stl', true, false],
        ['Edge.stl', false, false],
        ['Notch.stl', true, true],
      ],
    );
    const hit = first.objects[2].exclusionHits[0];
    assert.equal(hit.extruder, 0);
    assert.ok(hit.triangles.length > 0 && hit.triangles.length % 9 === 0, 'the intersecting surface is returned');
    const hitBox = bounds(hit.triangles);
    // The notch volume: x 80.5-119.5, y 0-28.6, z 0-5.
    assert.ok(hitBox.min[0] >= 80.4 && hitBox.max[0] <= 119.6 && hitBox.max[1] <= 28.7 && hitBox.max[2] <= 5.01, JSON.stringify(hitBox));

    // Moving objects reuses their loaded meshes; moving the notch cube out clears its hit.
    started = performance.now();
    const moved = runCheck(
      engine,
      checkJob(presets, [
        { name: 'Centre.stl', positions: translate(objects[0].positions, 5, 0) },
        { name: 'Edge.stl', positions: translate(objects[1].positions, -20, 0) },
        { name: 'Notch.stl', positions: translate(objects[2].positions, 0, 60) },
      ]),
    );
    const movedMs = performance.now() - started;
    assert.deepEqual(
      moved.objects.map((o) => [o.inside, o.exclusionHits.length]),
      [
        [true, 0],
        [true, 0],
        [true, 0],
      ],
    );
    t.diagnostic(`check: first ${ms(firstMs)}, after a move ${ms(movedMs)}`);
  });

  test('placement check of a Benchy stays fast while it moves', needsBenchy, async (t) => {
    const positions = await benchy([100, 90]);
    let started = performance.now();
    runCheck(engine, checkJob(presets, [{ name: 'Benchy.stl', positions }]));
    const firstMs = performance.now() - started;
    started = performance.now();
    const moved = runCheck(engine, checkJob(presets, [{ name: 'Benchy.stl', positions: translate(positions, 0, -70) }]));
    const movedMs = performance.now() - started;
    t.diagnostic(`Benchy check: first ${ms(firstMs)}, after a move ${ms(movedMs)} (spec target 50 ms)`);
    assert.equal(moved.objects[0].inside, true);
    assert.ok(moved.objects[0].exclusionHits.length > 0, 'a Benchy at y = 20 reaches into the notch');
  });

  // ---- Per-object settings (EngineObject.config)

  test("object settings: layer height 0.1 and 5 walls on one cube, as Orca's CLI slices it from a 3MF", (t) => {
    const sliced = slice(engine, presets, objectSettingsPlate());
    const { output } = sliced;
    report(t, 'object settings', sliced);
    t.diagnostic(`G-code: ${saveGcode('object-settings.gcode', output.gcode)}`);
    assertStatsMatchText(output);
    assert.equal(presets.process.layer_height, '0.2');
    assert.equal(presets.process.wall_loops, '3', 'the preset prints 3 walls: 1 outer and 2 inner');

    const layers = perObjectLayers(output.gcode);
    const a = layers.get('CubeA.stl'), b = layers.get('CubeB.stl');
    assert.ok(a && b, `objects in the G-code: ${[...layers.keys()].join(', ')}`);
    // As the CLI printed them: CubeA at 0.2, 0.3, 0.4 … (199 layers), CubeB at 0.2, 0.4 … (100).
    assert.deepEqual(a.zs, zSteps(0.2, 0.1, 20));
    assert.deepEqual(b.zs, zSteps(0.2, 0.2, 20));
    assert.equal(output.stats.layers, 199);

    // Z = 10: CubeA's 4 inner loops at half the height extrude what CubeB's 2 do (the CLI: 4.78
    // vs 4.76 mm of filament), along about twice the path; each has one outer loop.
    const feature = (layer: ObjectLayers, type: string) => layer.at10.get(type) ?? { e: 0, length: 0 };
    const [innerA, innerB] = [feature(a, 'Inner wall'), feature(b, 'Inner wall')];
    const [outerA, outerB] = [feature(a, 'Outer wall'), feature(b, 'Outer wall')];
    t.diagnostic(
      `Z 10 inner wall: CubeA ${innerA.e.toFixed(2)} mm over ${innerA.length.toFixed(0)} mm, CubeB ${innerB.e.toFixed(2)} mm over ${innerB.length.toFixed(0)} mm; ` +
        `outer wall ${outerA.length.toFixed(0)} / ${outerB.length.toFixed(0)} mm`,
    );
    assert.ok(Math.abs(innerA.e / innerB.e - 1) < 0.05, `inner wall filament ratio ${(innerA.e / innerB.e).toFixed(3)}`);
    assert.ok(innerA.length / innerB.length > 1.8 && innerA.length / innerB.length < 2.1, `inner wall path ratio ${(innerA.length / innerB.length).toFixed(3)}`);
    assert.ok(Math.abs(outerA.length / outerB.length - 1) < 0.02, `outer wall path ratio ${(outerA.length / outerB.length).toFixed(3)}`);

    // Every wall bead is as tall as its own object's layers (the preview draws Orca's heights).
    const { roles, extrusions } = output.toolpaths!;
    const heights = output.toolpathExtras!.height;
    const wallRoles = new Set(['Inner wall', 'Outer wall'].map((role) => roles.indexOf(role)));
    const seen = { a: new Set<number>(), b: new Set<number>() };
    for (let s = 0; s < extrusions.count; s++) {
      const z = extrusions.positions[s * 6 + 5];
      if (!wallRoles.has(extrusions.roleIndex[s]) || z < 0.25) continue; // the first layer is 0.2 for both
      const x = extrusions.positions[s * 6 + 3];
      if (x < 95) seen.a.add(Math.round(heights[s] * 1000));
      else seen.b.add(Math.round(heights[s] * 1000));
    }
    assert.deepEqual([...seen.a], [100], 'CubeA wall heights (µm)');
    assert.deepEqual([...seen.b], [200], 'CubeB wall heights (µm)');
  });

  test('object settings stay with their job: the next plate slices as if they never were', () => {
    const plain = objectSettingsPlate().map(({ name, positions }) => ({ name, positions }));
    const before = slice(engine, presets, plain).output;
    slice(engine, presets, objectSettingsPlate());
    const after = slice(engine, presets, plain).output;
    assert.equal(stableText(after.gcode), stableText(before.gcode));
    // No settings and empty settings are the same job.
    const empty = slice(engine, presets, objectSettingsPlate({})).output;
    assert.equal(stableText(empty.gcode), stableText(before.gcode));
  });

  test('an object setting Orca does not know, or cannot read, fails with -5 naming the object', () => {
    const cases: Array<[Record<string, string>, RegExp]> = [
      [{ layer_height: '0.1', no_such_setting: '1' }, /^The object "CubeA\.stl" has an unknown setting "no_such_setting"\.$/],
      [{ wall_loops: 'abc' }, /^The object "CubeA\.stl" has an invalid value for the setting "Wall loops" \(wall_loops\): "abc"\.$/],
      // The CLI's 3MF loader would quietly use the default pattern instead.
      [
        { sparse_infill_pattern: 'bogus' },
        /^The object "CubeA\.stl" has an invalid value for the setting "Sparse infill pattern" \(sparse_infill_pattern\): "bogus"\.$/,
      ],
      [{ enable_support: 'maybe' }, /\(enable_support\): "maybe"\.$/],
    ];
    for (const [settings, message] of cases) {
      const error = failure(() => slice(engine, presets, objectSettingsPlate(settings)));
      assert.equal(error.code, -5, error.message);
      assert.match(error.message, message);
      assert.deepEqual(error.objects, ['CubeA.stl']);
    }
    // A value that is not text never reaches Orca.
    const notText = objectSettingsPlate({ wall_loops: 5 as unknown as string });
    const error = failure(() => slice(engine, presets, notText));
    assert.equal(error.code, -5);
    assert.equal(error.message, 'The object "CubeA.stl": the value for "wall_loops" must be text.');
    assert.deepEqual(error.objects, ['CubeA.stl']);
    // The engine carries on.
    slice(engine, presets, [{ name: 'Cube.stl', positions: cube([100, 90]) }]);
  });

  test("an object setting outside Orca's limits fails with -5 naming the object, as it would in a preset", () => {
    // A layer height of 0 used to run the engine out of memory (Orca makes layers until it cannot).
    const invalid = (setting: string, value: string) => `The object "CubeA.stl" has an invalid value for the setting ${setting}: "${value}".`;
    const cases: Array<[Record<string, string>, string]> = [
      [{ layer_height: '0' }, `${invalid('"Layer height" (layer_height)', '0')} It must be more than 0.`],
      [{ layer_height: '-0.1' }, `${invalid('"Layer height" (layer_height)', '-0.1')} It must be more than 0.`],
      [{ wall_loops: '-1' }, `${invalid('"Wall loops" (wall_loops)', '-1')} It must be between 0 and 1000.`],
      [{ top_shell_layers: '-3' }, `${invalid('"Top solid layers" (top_shell_layers)', '-3')} It must be at least 0.`],
      [{ sparse_infill_density: '150%' }, `${invalid('"Sparse infill density" (sparse_infill_density)', '150%')} It must be between 0% and 100%.`],
      [{ support_threshold_angle: '200' }, `${invalid('"Threshold angle" (support_threshold_angle)', '200')} It must be between 0 and 90.`],
      [{ layer_height: '0.1', brim_width: '-5' }, `${invalid('"Brim width" (brim_width)', '-5')} It must be between 0 and 100.`],
    ];
    for (const [settings, message] of cases) {
      const started = performance.now();
      const error = failure(() => slice(engine, presets, objectSettingsPlate(settings)));
      assert.equal(error.code, -5, error.message);
      assert.equal(error.message, message);
      assert.deepEqual(error.objects, ['CubeA.stl']);
      assert.ok(performance.now() - started < 5000, 'refused before slicing');
    }
    // Values at the limits slice.
    const edges = slice(engine, presets, objectSettingsPlate({ wall_loops: '0', sparse_infill_density: '100%', support_threshold_angle: '90' }));
    assert.ok((edges.output.stats.layers ?? 0) > 0);
  });

  test('the placement check ignores object settings', () => {
    const checked = runCheck(engine, checkJob(presets, objectSettingsPlate({ no_such_setting: '1' })));
    assert.deepEqual(
      checked.objects.map((o) => [o.name, o.inside]),
      [
        ['CubeA.stl', true],
        ['CubeB.stl', true],
      ],
    );
  });

  // ---- configDefinitions(): Orca's option table for the settings catalogue

  test("configDefinitions() lists Orca's options, with labels, limits, modes, enums and defaults", (t) => {
    const started = performance.now();
    const text = engine.configDefinitions!();
    const defs = readConfigDefinitions(engine);
    t.diagnostic(`${Object.keys(defs.options).length} options, ${(text.length / 1024).toFixed(0)} KB, ${ms(performance.now() - started)}`);
    assert.equal(engine.configDefinitions!(), text, 'the same text every time');
    assert.equal(defs.format, 1);
    assert.deepEqual([defs.orcaVersion, defs.orcaCommit], [engine.version().orcaVersion, engine.version().orcaCommit]);

    const keys = Object.keys(defs.options);
    assert.ok(keys.length > 700, `${keys.length} options`);
    assert.deepEqual(keys, [...keys].sort(), 'options sorted by key');

    const layerHeight = defs.options.layer_height;
    assert.equal(layerHeight.type, 'float');
    assert.equal(layerHeight.label, 'Layer height');
    assert.equal(layerHeight.sidetext, 'mm');
    assert.equal(layerHeight.category, 'Quality');
    assert.equal(layerHeight.mode, 'simple');
    assert.equal(layerHeight.min, 0);
    assert.equal(layerHeight.max, undefined, 'no upper limit');
    assert.equal(layerHeight.default, '0.2');
    assert.match(layerHeight.tooltip, /height for each layer/);

    const pattern = defs.options.sparse_infill_pattern;
    assert.equal(pattern.type, 'enum');
    assert.equal(pattern.label, 'Sparse infill pattern');
    assert.equal(pattern.enumValues.length, pattern.enumLabels.length);
    assert.equal(pattern.enumLabels[pattern.enumValues.indexOf('gyroid')], 'Gyroid');
    assert.ok(pattern.enumValues.includes(pattern.default as string), `default ${String(pattern.default)}`);
    assert.ok(pattern.enumValues.every((value) => value in pattern.enumKeys!), 'every listed value is accepted');

    // Orca's JSON encoding: vectors as arrays of text, nullable per-filament overrides.
    assert.deepEqual(defs.options.printable_area.default, ['0x0', '200x0', '200x200', '0x200']);
    assert.equal(defs.options.filament_retraction_length.nullable, true);
    assert.equal(defs.options.machine_start_gcode.multiline, true);
    assert.equal(defs.options.wall_loops.max, 1000);
    assert.equal(defs.options.sparse_infill_density.type, 'percent');
    // Enum defaults by name, as a preset stores them (a vector of enums once came out as [""]).
    assert.deepEqual(defs.options.z_hop_types.default, ['Slope Lift']);
    assert.deepEqual(defs.options.retract_lift_enforce.default, ['All Surfaces']);
    assert.deepEqual(defs.options.extruder_type.default, ['Direct Drive']);
    let enumOptions = 0;
    for (const [key, def] of Object.entries(defs.options)) {
      assert.notEqual(def.type, 'none', key);
      if ((def.type !== 'enum' && def.type !== 'enums') || def.default === undefined) continue;
      enumOptions++;
      const names = typeof def.default === 'string' ? [def.default] : def.default;
      assert.ok(names.length > 0, `${key} has a default`);
      for (const name of names) {
        const known = (def.enumKeys !== undefined && name in def.enumKeys) || (def.nullable === true && name === 'nil');
        assert.ok(known, `${key} default ${JSON.stringify(def.default)}`);
      }
    }
    assert.ok(enumOptions > 60, `${enumOptions} enum options with defaults`);
    assert.equal(defs.options.printer_technology.technology, 'any');
    assert.ok(!('supports_enable' in defs.options) && !('exposure_time' in defs.options), 'no SLA options');

    // Key sets, each sorted.
    const sets: Array<[string, string[]]> = [
      ...Object.entries(defs.presetKeys),
      ...Object.entries(defs.variantKeys),
      ['extruder', defs.extruderKeys],
      ['extruderRetract', defs.extruderRetractKeys],
      ['filamentOverride', defs.filamentOverrideKeys],
      ['object', defs.objectKeys],
      ['region', defs.regionKeys],
    ];
    for (const [name, list] of sets) {
      assert.ok(list.length > 0, `${name} keys`);
      assert.deepEqual(list, [...new Set(list)].sort(), `${name} keys sorted and unique`);
    }
    t.diagnostic(sets.map(([name, list]) => `${name} ${list.length}`).join(', '));
    assert.ok(defs.presetKeys.process.includes('layer_height') && defs.presetKeys.filament.includes('nozzle_temperature'));
    assert.ok(defs.presetKeys.machine.includes('printable_area') && defs.presetKeys.machine.includes('machine_max_speed_x'));
    assert.ok(defs.extruderKeys.includes('nozzle_diameter') && defs.filamentOverrideKeys.includes('filament_retraction_length'));
    assert.ok(defs.objectKeys.includes('layer_height') && defs.regionKeys.includes('wall_loops'));
    // Every per-object key is an option, and the settings the object tests set are per-object keys.
    const perObject = new Set([...defs.objectKeys, ...defs.regionKeys]);
    for (const key of perObject) assert.ok(key in defs.options, key);
    for (const key of ['layer_height', 'wall_loops', 'sparse_infill_pattern', 'sparse_infill_density', 'enable_support', 'top_shell_layers', 'support_threshold_angle', 'brim_width']) {
      assert.ok(perObject.has(key), key);
    }
  });
});
