// End-to-end tests of the built engine under plain Node, through the same loader and marshalling
// code the browser worker uses (web/src/engine/worker.ts). Skipped until the engine is built.
//
//   node --test engine/test/engine.test.ts                    # web/public/engine/engine-st.mjs
//   ENGINE_VARIANT=mt node --test engine/test/engine.test.ts
//   ENGINE_DIR=$ORCA_WASM_ROOT/build-st/out node --test engine/test/engine.test.ts
//
// Besides "does it slice", every G-code the engine returns is read back with the server's footer
// parser (server/gcodeStats.ts) and the UI's G-code parser (web/src/gcode/parse.ts): the stats must
// be identical, and the toolpaths the engine builds from Orca's GCodeProcessor must match what the
// parser draws from the text. The G-code is written to ENGINE_TEST_OUT for inspection.
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { before, describe, test, type TestContext } from 'node:test';
import { parseStatsText } from '../../server/gcodeStats.ts';
import type { GcodeStats } from '../../shared/types.ts';
import { parseGcode, sizeCode, type ParsedGcode } from '../../web/src/gcode/parse.ts';
import type { CheckOutput, EngineWarning, SliceOutput } from '../../web/src/engine/protocol.ts';
import { EngineJobError, runCheck, runSlice, type OrcaEngineModule } from '../../web/src/engine/worker.ts';
import {
  benchy,
  benchyAvailable,
  benchyPath,
  bounds,
  checkJob,
  cube,
  cylinder,
  engineBuilt,
  engineModulePath,
  flatPresets,
  m1ResourcesAvailable,
  m1Presets,
  ms,
  outDir,
  sliceJob,
  startEngine,
  translate,
  variant,
  X1C,
  type Presets,
} from './fixtures.ts';

const suite = engineBuilt && m1ResourcesAvailable ? describe : describe.skip;
if (!engineBuilt) console.log(`# ${engineModulePath} not found: build the engine first (engine/scripts/build.sh).`);
else if (!m1ResourcesAvailable) console.log(`# No Muon3D M1 profiles in ${process.env.ORCA_RESOURCES}: set ORCA_WASM_ROOT, ORCA_SRC or ORCA_RESOURCES.`);
// A fresh clone has no data/ folder: the Benchy tests are skipped rather than failed.
const needsBenchy = benchyAvailable ? {} : { skip: `${benchyPath} not found` };

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface Sliced {
  output: SliceOutput;
  progress: Array<[number, string]>;
  warnings: EngineWarning[];
  wallMs: number;
}

function slice(engine: OrcaEngineModule, presets: Presets, objects: Array<{ name: string; positions: Float32Array }>): Sliced {
  const progress: Array<[number, string]> = [];
  const warnings: EngineWarning[] = [];
  const started = performance.now();
  const output = runSlice(engine, sliceJob(presets, objects), (p, m) => progress.push([p, m]), (w) => warnings.push(w));
  return { output, progress, warnings, wallMs: performance.now() - started };
}

/** The EngineError a job fails with (fails the test if it succeeds or the engine itself breaks). */
function failure(run: () => unknown) {
  try {
    run();
  } catch (err) {
    if (err instanceof EngineJobError) return err.error;
    throw err;
  }
  assert.fail('expected the job to fail');
}

/** What the server would show for this G-code: its header/footer parse. */
function statsFromText(gcode: Uint8Array): GcodeStats {
  const decoder = new TextDecoder();
  const head = decoder.decode(gcode.subarray(0, 16 * 1024));
  const tail = decoder.decode(gcode.subarray(Math.max(0, gcode.length - 512 * 1024)));
  return parseStatsText(head, tail);
}

function saveGcode(name: string, gcode: Uint8Array): string {
  const dir = path.join(outDir, `engine-${variant}`);
  mkdirSync(dir, { recursive: true });
  const file = path.join(dir, name);
  writeFileSync(file, gcode);
  return file;
}

/** The G-code without the lines that legitimately differ between runs. */
function stableText(gcode: Uint8Array): string {
  return new TextDecoder()
    .decode(gcode)
    .split('\n')
    .filter((line) => !line.startsWith('; generated by '))
    .join('\n');
}

function report(t: TestContext, label: string, { output, wallMs }: Sliced): void {
  const { stats, timings, toolpaths } = output;
  t.diagnostic(
    `${label}: ${ms(wallMs)} (load ${ms(timings.load)}, slice ${ms(timings.slice)}, export ${ms(timings.export)}); ` +
      `${(output.gcode.length / 1e6).toFixed(2)} MB G-code; ${stats.layers} layers, ${stats.printTimeText}, ` +
      `${stats.filamentMm} mm / ${stats.filamentG} g filament, max Z ${stats.maxZ}` +
      (toolpaths ? `; ${toolpaths.extrusions.count.toLocaleString('en')} extrusion + ${toolpaths.travels.count.toLocaleString('en')} travel segments` : ''),
  );
}

/** Progress must be monotonic, within 0-100, and end near the top. */
function assertProgress(progress: Array<[number, string]>): void {
  assert.ok(progress.length > 3, 'progress was reported');
  for (let i = 1; i < progress.length; i++) assert.ok(progress[i][0] >= progress[i - 1][0], `progress went back at ${JSON.stringify(progress[i])}`);
  assert.ok(progress.every(([p]) => p >= 0 && p <= 100));
  assert.ok(progress.at(-1)![0] >= 95, `last progress ${JSON.stringify(progress.at(-1))}`);
}

/** Stats must mean exactly what the server reads from the same G-code. */
function assertStatsMatchText(output: SliceOutput): void {
  assert.deepEqual(output.stats, statsFromText(output.gcode), 'stats differ from the G-code header/footer');
  const s = output.stats;
  assert.ok(s.printTimeSeconds! > 0 && s.filamentMm! > 0 && s.filamentG! > 0 && s.layers! > 0 && s.maxZ! > 0, JSON.stringify(s));
}

/**
 * The engine's toolpaths (from Orca's GCodeProcessor) against the UI parser's reading of the same
 * G-code text: same layers and roles, near-identical lengths and segment counts.
 */
function assertToolpathsMatchParser(t: TestContext, output: SliceOutput): void {
  const engine = output.toolpaths;
  assert.ok(engine, 'toolpaths were requested');
  const parsed = parseGcode(output.gcode);

  assert.equal(engine.layerCount, parsed.layerCount, 'layer count');
  assert.equal(engine.layerZ.length, engine.layerCount);
  assert.equal(engine.extrusions.layerStart.length, engine.layerCount + 1);
  assert.equal(engine.extrusions.layerStart[engine.layerCount], engine.extrusions.count);
  assert.equal(engine.travels.layerStart[engine.layerCount], engine.travels.count);
  assert.equal(engine.extrusions.positions.length, engine.extrusions.count * 6);
  assert.equal(engine.extrusions.roleIndex.length, engine.extrusions.count);
  assert.equal(engine.extrusions.width.length, engine.extrusions.count);
  assert.equal(engine.extrusions.height.length, engine.extrusions.count);
  for (let l = 1; l <= engine.layerCount; l++) assert.ok(engine.extrusions.layerStart[l] >= engine.extrusions.layerStart[l - 1]);
  for (const array of Object.values(output.toolpathExtras!)) assert.equal((array as ArrayLike<number>).length, engine.extrusions.count);

  assert.deepEqual([...engine.roles].sort(), [...parsed.roles].sort(), 'roles');
  for (const [i, role] of engine.roles.entries()) {
    const theirs = parsed.roleLength[parsed.roles.indexOf(role)];
    const ours = engine.roleLength[i];
    assert.ok(Math.abs(ours - theirs) <= Math.max(1, theirs * 0.02), `${role}: ${ours.toFixed(1)} mm vs parser ${theirs.toFixed(1)} mm`);
  }

  let sameZ = 0;
  for (let l = 0; l < engine.layerCount; l++) if (Math.abs(engine.layerZ[l] - parsed.layerZ[l]) < 2e-3) sameZ++;
  assert.ok(sameZ >= engine.layerCount * 0.95, `layer Z agrees on ${sameZ}/${engine.layerCount} layers`);

  const ratio = engine.extrusions.count / parsed.extrusions.count;
  t.diagnostic(
    `segments: engine ${engine.extrusions.count} extrusions / ${engine.travels.count} travels, ` +
      `parser ${parsed.extrusions.count} / ${parsed.travels.count}; line width ${engine.lineWidth} vs ${parsed.lineWidth}`,
  );
  // One segment per G-code move on both sides (arcs, off in the M1 presets, would differ a little:
  // Orca and the parser tessellate them differently).
  assert.ok(Math.abs(ratio - 1) < 0.005, `extrusion segments: engine ${engine.extrusions.count}, parser ${parsed.extrusions.count}`);
  assert.equal(engine.lineWidth, parsed.lineWidth, 'dominant line width');
  assertBeadsMatchParser(t, engine, parsed);
  // The engine's height codes are the processor's own heights (toolpathExtras.height, in mm).
  const heights = output.toolpathExtras!.height;
  for (let s = 0; s < engine.extrusions.count; s++) {
    if (engine.extrusions.height[s] !== sizeCode(heights[s])) assert.fail(`segment ${s}: height code ${engine.extrusions.height[s]} for ${heights[s]} mm`);
  }
  assert.ok(engine.bounds && parsed.bounds);
  for (let a = 0; a < 2; a++) {
    assert.ok(Math.abs(engine.bounds.min[a] - parsed.bounds.min[a]) < 0.05, `bounds.min[${a}]`);
    assert.ok(Math.abs(engine.bounds.max[a] - parsed.bounds.max[a]) < 0.05, `bounds.max[${a}]`);
  }
}

/**
 * Every bead as wide and as tall as Orca draws it: the width and height GCodeProcessor gave each
 * move (the engine's toolpaths) against what the parser works out from the text, segment by
 * segment, within one size code (0.01 mm; float against double rounding).
 */
function assertBeadsMatchParser(t: TestContext, engine: ParsedGcode, parsed: ParsedGcode): void {
  const ours = engine.extrusions, theirs = parsed.extrusions;
  let compared = 0;
  const off: string[] = [];
  for (let l = 0; l < engine.layerCount; l++) {
    const first = ours.layerStart[l], firstParsed = theirs.layerStart[l];
    const count = ours.layerStart[l + 1] - first;
    // Where a layer has as many segments on both sides, they are the same moves in the same order.
    if (count !== theirs.layerStart[l + 1] - firstParsed) continue;
    for (let k = 0; k < count; k++) {
      const s = first + k, p = firstParsed + k;
      const sameEnd = Math.abs(ours.positions[s * 6 + 3] - theirs.positions[p * 6 + 3]) < 1e-3 && Math.abs(ours.positions[s * 6 + 4] - theirs.positions[p * 6 + 4]) < 1e-3;
      if (!sameEnd) continue;
      compared++;
      if (Math.abs(ours.width[s] - theirs.width[p]) > 1 || Math.abs(ours.height[s] - theirs.height[p]) > 1) {
        off.push(`layer ${l} ${engine.roles[ours.roleIndex[s]]}: width ${ours.width[s]}/${theirs.width[p]}, height ${ours.height[s]}/${theirs.height[p]}`);
      }
    }
  }
  t.diagnostic(`bead widths and heights compared on ${compared} of ${ours.count} segments, ${off.length} differ`);
  assert.ok(compared >= ours.count * 0.95, `only ${compared} of ${ours.count} segments line up with the parser's`);
  assert.deepEqual(off.slice(0, 10), [], `${off.length} segments differ (engine/parser, size codes)`);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

suite(`engine-${variant}`, () => {
  let engine: OrcaEngineModule;
  let presets: Presets;

  before(async () => {
    const started = await startEngine();
    engine = started.engine;
    presets = await m1Presets();
    console.log(`# engine-${variant} ready in ${ms(started.initMs)}: OrcaSlicer ${engine.version().orcaVersion} (${engine.version().orcaCommit})`);
  });

  test('reports its Orca version', () => {
    const version = engine.version();
    assert.match(version.orcaVersion, /^\d+\.\d+\.\d+/);
    assert.equal(typeof version.orcaCommit, 'string');
  });

  test('slices a 20 mm cube at [100, 90]', (t) => {
    const sliced = slice(engine, presets, [{ name: 'Cube.stl', positions: cube([100, 90]) }]);
    const { output } = sliced;
    report(t, 'cube', sliced);
    t.diagnostic(`G-code: ${saveGcode('cube.gcode', output.gcode)}`);

    const text = new TextDecoder().decode(output.gcode);
    assert.match(text, /^; generated by OrcaSlicer 2\.5\.0-dev/m);
    assert.match(text, /EXCLUDE_OBJECT_DEFINE NAME=Cube\.stl/, 'object named as on the server');
    assert.equal(output.stats.maxZ, 20);
    assert.ok(Math.abs(output.stats.layers! - 100) <= 1, `layers ${output.stats.layers}`);
    assertProgress(sliced.progress);
    assertStatsMatchText(output);
    assertToolpathsMatchParser(t, output);
    assert.deepEqual(output.warnings, sliced.warnings, 'every warning was also streamed');
  });

  test('slicing the same plate again gives the same G-code (a fresh Print per job)', () => {
    const objects = [{ name: 'Cube.stl', positions: cube([100, 90]) }];
    const first = slice(engine, presets, objects).output;
    const second = slice(engine, presets, objects).output;
    assert.equal(stableText(second.gcode), stableText(first.gcode));
  });

  test('slices Benchy at [100, 90]', needsBenchy, async (t) => {
    const positions = await benchy([100, 90]);
    const size = bounds(positions);
    const sliced = slice(engine, presets, [{ name: 'Benchy.stl', positions }]);
    const { output } = sliced;
    report(t, 'benchy', sliced);
    t.diagnostic(`G-code: ${saveGcode('benchy.gcode', output.gcode)}`);

    const height = size.max[2] - size.min[2];
    assert.ok(Math.abs(output.stats.maxZ! - height) < 0.25, `max Z ${output.stats.maxZ} for a ${height.toFixed(2)} mm model`);
    assert.ok(Math.abs(output.stats.layers! - height / 0.2) <= 2, `layers ${output.stats.layers}`);
    assert.ok(output.stats.printTimeSeconds! > 600, 'a Benchy takes more than 10 minutes');
    assertProgress(sliced.progress);
    assertStatsMatchText(output);
    assertToolpathsMatchParser(t, output);
  });

  test('support, ironing, gap fill and combined infill: every bead as wide and as tall as Orca draws it', needsBenchy, async (t) => {
    const positions = await benchy([100, 90]);
    const process = {
      ...presets.process,
      enable_support: '1',
      support_type: 'normal(auto)',
      ironing_type: 'top',
      wall_generator: 'classic',
      gap_fill_target: 'everywhere',
      infill_combination: '1',
    };
    const sliced = slice(engine, { ...presets, process }, [{ name: 'Benchy.stl', positions }]);
    const { output } = sliced;
    report(t, 'benchy with support and ironing', sliced);
    assertToolpathsMatchParser(t, output);

    // Heights that are not the layer's: GCodeProcessor's, as Orca's preview draws them.
    const { roles, extrusions } = output.toolpaths!;
    const heightsOf = (role: string) => {
      const index = roles.indexOf(role);
      assert.ok(index >= 0, `no ${role}`);
      return new Set(extrusions.height.filter((_, s) => extrusions.roleIndex[s] === index));
    };
    assert.deepEqual(heightsOf('Custom'), new Set([15]), 'the purge line, 0.15 mm above the bed');
    assert.deepEqual(heightsOf('Bridge'), new Set([40]), 'bridges, as tall as the nozzle is wide');
    assert.ok(heightsOf('Sparse infill').has(40), 'infill combined over two layers');
    assert.deepEqual(heightsOf('Ironing'), new Set([1]), 'ironing, a film');
    assert.ok(heightsOf('Support').size > 3, 'support layers of their own heights');
    assert.ok(heightsOf('Gap infill').size > 0);
  });

  test('a cube in the M1 front notch fails with -64 (exclusion volume)', () => {
    const error = failure(() => slice(engine, presets, [{ name: 'Notch.stl', positions: cube([100, 14]) }]));
    assert.equal(error.code, -64, error.message);
    assert.match(error.message, /exclusion volume/i);
    assert.deepEqual(error.objects, ['Notch.stl']);
  });

  test('cubes beside the notch slice, and the skirt crossing it is only a warning', (t) => {
    const sliced = slice(engine, presets, [
      { name: 'Left.stl', positions: cube([40, 15]) },
      { name: 'Right.stl', positions: cube([160, 15]) },
    ]);
    report(t, 'notch neighbours', sliced);
    const kinds = sliced.output.warnings.map((w) => `${w.kind}: ${w.message}`);
    t.diagnostic(`warnings: ${kinds.length ? kinds.join(' | ') : 'none'}`);
    // Spec §7 expects the fork's path check to flag the skirt; whether it does depends on the
    // branch's skirt/travel handling, so this is reported rather than asserted.
  });

  test('an object partly off the bed fails with -52', () => {
    const error = failure(() =>
      slice(engine, presets, [
        { name: 'Cube.stl', positions: cube([100, 90]) },
        { name: 'Edge.stl', positions: cube([195, 90]) },
      ]),
    );
    assert.equal(error.code, -52, error.message);
    assert.deepEqual(error.objects, ['Edge.stl']);
  });

  test('a plate with nothing fully on the bed fails with -50', () => {
    // As in the CLI, "nothing inside" is checked first, so a lone object over the edge is -50 too.
    for (const center of [
      [400, 400],
      [195, 90],
    ] as Array<[number, number]>) {
      const error = failure(() => slice(engine, presets, [{ name: 'Far.stl', positions: cube(center) }]));
      assert.equal(error.code, -50, error.message);
    }
  });

  test('an unflattened preset fails with -5', () => {
    const unflattened = { ...presets, process: { ...presets.process, inherits: 'fdm_process_muon_m1_common' } };
    const error = failure(() => slice(engine, unflattened, [{ name: 'Cube.stl', positions: cube([100, 90]) }]));
    assert.equal(error.code, -5, error.message);
    assert.match(error.message, /inherits/);
  });

  test('an empty mesh fails with -6 and the engine carries on', () => {
    const error = failure(() => slice(engine, presets, [{ name: 'Empty.stl', positions: new Float32Array(0) }]));
    assert.equal(error.code, -6, error.message);
    slice(engine, presets, [{ name: 'Cube.stl', positions: cube([100, 90]) }]);
  });

  test('a mesh without one usable triangle fails with -6 and says so', () => {
    for (const [name, positions] of [
      ['Point.stl', new Float32Array(90).fill(5)], // every vertex the same point: zero area
      ['NaN.stl', new Float32Array(108).fill(NaN)],
    ] as Array<[string, Float32Array]>) {
      const error = failure(() => slice(engine, presets, [{ name, positions }]));
      assert.equal(error.code, -6, error.message);
      assert.match(error.message, /has no usable triangles/);
      assert.deepEqual(error.objects, [name]);
    }
  });

  test('a preset value Orca cannot read fails with -5 naming the key, not a key it then lost', () => {
    // Orca's load_from_json stops reading the file at an array it cannot parse, and skips numbers.
    const cases: Array<[string, (p: Presets) => void, string]> = [
      ['process', (p) => (p.process.top_surface_acceleration = [null] as unknown as string[]), 'top_surface_acceleration'],
      ['machine', (p) => (p.machine.nozzle_diameter = ['0.4', 3] as unknown as string[]), 'nozzle_diameter'],
      ['filament', (p) => (p.filaments[0].during_print_exhaust_fan_speed = [null] as unknown as string[]), 'during_print_exhaust_fan_speed'],
      ['process', (p) => (p.process.layer_height = 0.2 as unknown as string), 'layer_height'],
    ];
    for (const [type, mutate, key] of cases) {
      const broken = structuredClone(presets);
      mutate(broken);
      const error = failure(() => slice(engine, broken, [{ name: 'Cube.stl', positions: cube([100, 90]) }]));
      assert.equal(error.code, -5, error.message);
      assert.ok(error.message.startsWith(`The ${type} preset "`) && error.message.includes(`"${key}"`), error.message);
    }
    // A value Orca itself rejects: its text, without the exception type load_from_json puts first.
    const notANumber = structuredClone(presets);
    notANumber.process.layer_height = 'abc';
    const error = failure(() => slice(engine, notANumber, [{ name: 'Cube.stl', positions: cube([100, 90]) }]));
    assert.equal(error.code, -5, error.message);
    assert.equal(error.message, 'The process preset could not be parsed: Invalid value provided for parameter layer_height: abc');
  });

  test('a setting that is not a finite number fails with -100 and names the setting', () => {
    // "1e400" loads as infinity; Orca only fails when it writes the G-code's config block, like the CLI.
    const broken = structuredClone(presets);
    broken.filaments[0].filament_retraction_length = ['1e400'];
    const error = failure(() => slice(engine, broken, [{ name: 'Cube.stl', positions: cube([100, 90]) }]));
    assert.equal(error.code, -100, error.message);
    assert.match(error.message, /"filament_retraction_length"/);
  });

  test('Bambu Lab G-code is the same in every job: label ids 1..n, object ids from 0', async () => {
    const x1c = await flatPresets(X1C);
    const plate = [
      { name: 'Cube.stl', positions: cube([100, 90], 15) },
      { name: 'Cube_2.stl', positions: cube([140, 90], 15) },
    ];
    const first = slice(engine, x1c, plate).output;
    // Any job in between moves Orca's process-wide object ids on.
    slice(engine, presets, [{ name: 'Cube.stl', positions: cube([100, 90]) }]);
    const second = slice(engine, x1c, plate).output;

    const text = new TextDecoder().decode(first.gcode);
    assert.match(text, /^; model label id: 1,2$/m);
    assert.match(text, /^; start printing object, unique label id: 2$/m);
    assert.match(text, /^; printing object Cube\.stl id:0 copy 0$/m);
    assert.match(text, /^; printing object Cube_2\.stl id:1 copy 0$/m);
    assert.equal(stableText(second.gcode), stableText(first.gcode));
  });

  test('arc fitting turns walls into G2/G3 when the overhang fan does not need them point by point', (t) => {
    const walls = (overhangFan: '0' | '1') => {
      const arcs = structuredClone(presets);
      arcs.process.enable_arc_fitting = '1';
      arcs.filaments[0].enable_overhang_bridge_fan = [overhangFan];
      const { output } = slice(engine, arcs, [{ name: 'Cylinder.stl', positions: cylinder([100, 90], 15, 10) }]);
      assertStatsMatchText(output);
      let role = '';
      let moves = 0;
      let arcMoves = 0;
      for (const line of new TextDecoder().decode(output.gcode).split('\n')) {
        if (line.startsWith(';TYPE:')) role = line.slice(6);
        else if (/wall/i.test(role) && /^G[123] .*E/.test(line)) {
          moves++;
          if (line[1] !== '1') arcMoves++;
        }
      }
      return { moves, arcMoves };
    };
    const plain = walls('0');
    assert.ok(plain.arcMoves > plain.moves / 4, `${plain.arcMoves} of ${plain.moves} wall moves are arcs`);
    // Orca since 68ce4da19f / e8115658e0 writes every wall point by point while the overhang fan is
    // on, so arc fitting then stops at the walls (engine/PATCHES.md); reported, not asserted.
    const fan = walls('1');
    t.diagnostic(`wall arcs: ${plain.arcMoves}/${plain.moves} moves with the overhang fan off, ${fan.arcMoves}/${fan.moves} with it on`);
  });

  test('placement check: inside, over the edge, and in the notch', (t) => {
    const objects = [
      { name: 'Centre.stl', positions: cube([100, 90]) },
      { name: 'Edge.stl', positions: cube([195, 90]) },
      { name: 'Notch.stl', positions: cube([100, 14]) },
    ];
    let started = performance.now();
    const first: CheckOutput = runCheck(engine, checkJob(presets, objects));
    const firstMs = performance.now() - started;

    assert.deepEqual(
      first.objects.map((o) => [o.name, o.inside, o.exclusionHits.length > 0]),
      [
        ['Centre.stl', true, false],
        ['Edge.stl', false, false],
        ['Notch.stl', true, true],
      ],
    );
    const hit = first.objects[2].exclusionHits[0];
    assert.equal(hit.extruder, 0);
    assert.ok(hit.triangles.length > 0 && hit.triangles.length % 9 === 0, 'the intersecting surface is returned');
    const hitBox = bounds(hit.triangles);
    // The notch volume: x 80.5-119.5, y 0-28.6, z 0-5.
    assert.ok(hitBox.min[0] >= 80.4 && hitBox.max[0] <= 119.6 && hitBox.max[1] <= 28.7 && hitBox.max[2] <= 5.01, JSON.stringify(hitBox));

    // Moving objects reuses their loaded meshes; moving the notch cube out clears its hit.
    started = performance.now();
    const moved = runCheck(
      engine,
      checkJob(presets, [
        { name: 'Centre.stl', positions: translate(objects[0].positions, 5, 0) },
        { name: 'Edge.stl', positions: translate(objects[1].positions, -20, 0) },
        { name: 'Notch.stl', positions: translate(objects[2].positions, 0, 60) },
      ]),
    );
    const movedMs = performance.now() - started;
    assert.deepEqual(
      moved.objects.map((o) => [o.inside, o.exclusionHits.length]),
      [
        [true, 0],
        [true, 0],
        [true, 0],
      ],
    );
    t.diagnostic(`check: first ${ms(firstMs)}, after a move ${ms(movedMs)}`);
  });

  test('placement check of a Benchy stays fast while it moves', needsBenchy, async (t) => {
    const positions = await benchy([100, 90]);
    let started = performance.now();
    runCheck(engine, checkJob(presets, [{ name: 'Benchy.stl', positions }]));
    const firstMs = performance.now() - started;
    started = performance.now();
    const moved = runCheck(engine, checkJob(presets, [{ name: 'Benchy.stl', positions: translate(positions, 0, -70) }]));
    const movedMs = performance.now() - started;
    t.diagnostic(`Benchy check: first ${ms(firstMs)}, after a move ${ms(movedMs)} (spec target 50 ms)`);
    assert.equal(moved.objects[0].inside, true);
    assert.ok(moved.objects[0].exclusionHits.length > 0, 'a Benchy at y = 20 reaches into the notch');
  });
});
