// The plates the slice goldens are recorded with (test/goldens/slices.json): each a preset fixture and
// placed objects, as protocol v2 SliceParams. tools/goldens/record-slices-v1.mjs sliced them with the
// v0.1.0 release (its own host, protocol v1); the conformance suite slices them through the v2 host and
// requires the same G-code (the "; generated by" line aside, which holds the time).
import { readFileSync } from 'node:fs';
import type { Config } from '../../packages/protocol/src/data.ts';
import type { SliceParams } from '../../packages/protocol/src/ops.ts';
import { box, cube, cylinder } from '../fixtures.ts';

interface PresetFixture {
  machine: Config;
  process: Config;
  filaments: Config[];
}

const fixture = (id: string): PresetFixture => {
  const { machine, process, filaments } = JSON.parse(readFileSync(new URL(`../fixtures/presets/${id}.json`, import.meta.url), 'utf8')) as PresetFixture;
  return { machine, process, filaments };
};

export interface Plate {
  id: string;
  params(): SliceParams;
}

const mesh = (positions: Float32Array) => ({ positions });

export const PLATES: readonly Plate[] = [
  {
    id: 'm1-cube',
    params: () => ({ configs: fixture('muon3d-m1-0.4'), objects: [{ name: 'Cube.stl', mesh: mesh(cube([100, 90])) }] }),
  },
  {
    id: 'm1-object-settings',
    params: () => ({
      configs: fixture('muon3d-m1-0.4'),
      objects: [
        { name: 'CubeA.stl', mesh: mesh(cube([60, 60])), config: { layer_height: '0.1', wall_loops: '5' } },
        { name: 'CubeB.stl', mesh: mesh(cube([130, 60])) },
      ],
    }),
  },
  {
    id: 'm1-two-cubes',
    params: () => ({
      configs: fixture('muon3d-m1-0.4'),
      objects: [
        { name: 'Cube.stl', mesh: mesh(cube([100, 90], 15)) },
        { name: 'Cube_2.stl', mesh: mesh(cube([140, 90], 15)) },
      ],
    }),
  },
  {
    id: 'm1-cylinder-arcs',
    params: () => {
      const configs = fixture('muon3d-m1-0.4');
      return { configs: { ...configs, process: { ...configs.process, enable_arc_fitting: '1' } }, objects: [{ name: 'Cylinder.stl', mesh: mesh(cylinder([100, 90], 15, 10)) }] };
    },
  },
  {
    id: 'x1c-box',
    params: () => ({ configs: fixture('bbl-x1c-0.4'), objects: [{ name: 'Box.stl', mesh: mesh(box([30, 20, 12], [128, 128])) }] }),
  },
];

/** The G-code as the goldens compare it: without the header line that holds the time it was made. */
export function comparable(gcode: Uint8Array): string {
  return new TextDecoder().decode(gcode).replace(/^; generated by .*$/m, '; generated by');
}
