#!/usr/bin/env bash
# Compile-only check of the bridge sources (em++ -fsyntax-only) against Orca's headers and the
# dependency sources, without the engine build. Useful while libslic3r itself is not built yet,
# and as a quick check after editing the bridge.
#
#   bash engine/bridge/check-syntax.sh            # single-threaded variant (serial TBB shim)
#   VARIANT=mt bash engine/bridge/check-syntax.sh # pthreads + oneTBB headers
#   bash engine/bridge/check-syntax.sh engine.cpp # selected files only
#
# Paths default to the layout in engine/README.md; override with ORCA_WASM_ROOT / ORCA_SRC.
set -euo pipefail

VARIANT=${VARIANT:-st}
ROOT=${ORCA_WASM_ROOT:-$HOME/OrcaWasm}
ORCA=${ORCA_SRC:-$ROOT/orca}
DEPS=$ROOT/deps-src
HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -W 2>/dev/null || pwd)
SHIMS=$HERE/../shims
GEN=$ROOT/bridge-check/$VARIANT   # generated libslic3r_version.h + response file

# Toolchain, as in engine/deps/build-deps.sh (emsdk 6 ships .exe launchers Git Bash runs directly).
export EMSDK=$ROOT/emsdk
export EM_CONFIG=$EMSDK/.emscripten
export EMSDK_NODE=${EMSDK_NODE:-$(ls -d "$EMSDK"/node/*/node.exe 2>/dev/null | head -1)}
export EMSDK_PYTHON=${EMSDK_PYTHON:-$(ls -d "$EMSDK"/python/*/python.exe 2>/dev/null | head -1)}
export EM_CACHE=${EM_CACHE:-$EMSDK/upstream/emscripten/cache}
export PATH="/${ROOT:0:1}${ROOT:2}/emsdk/upstream/emscripten:$PATH"
EMXX=${EMXX:-em++}

mkdir -p "$GEN"
# libslic3r_version.h is generated by Orca's CMake from version.inc; the values that reach the
# G-code must match the native build ("; generated by OrcaSlicer 2.5.0-dev …").
SOFTFEVER_VERSION=$(sed -n 's/^set(SoftFever_VERSION "\(.*\)")/\1/p' "$ORCA/version.inc")
SLIC3R_VERSION=$(sed -n 's/^set(SLIC3R_VERSION "\(.*\)")/\1/p' "$ORCA/version.inc")
cat > "$GEN/libslic3r_version.h" <<EOF
#ifndef __SLIC3R_VERSION_H
#define __SLIC3R_VERSION_H
#define SLIC3R_APP_NAME "OrcaSlicer"
#define SLIC3R_APP_KEY "OrcaSlicer"
#define SLIC3R_VERSION "$SLIC3R_VERSION"
#define SoftFever_VERSION "$SOFTFEVER_VERSION"
#define SLIC3R_BUILD_ID "syntax-check"
#define BBL_INTERNAL_TESTING 0
#define ORCA_CHECK_GCODE_PLACEHOLDERS 0
#endif
EOF

FLAGS=(
  -std=c++17 -fsyntax-only -fsigned-char
  -fwasm-exceptions -sSUPPORT_LONGJMP=wasm -sWASM_LEGACY_EXCEPTIONS=1
  -DNDEBUG -DUSE_TBB -DTBB_USE_CAPTURED_EXCEPTION=0
  -DCGAL_ALWAYS_ROUND_TO_NEAREST -DCGAL_DISABLE_GMP
  -DLIBNEST2D_THREADING_tbb -DLIBNEST2D_STATIC -DLIBNEST2D_OPTIMIZER_nlopt -DLIBNEST2D_GEOMETRIES_libslic3r
  -Wall -Wno-unused-function
)
if [[ $VARIANT == mt ]]; then
  FLAGS+=(-pthread -isystem "$DEPS/oneTBB-2021.12.0/include")
else
  FLAGS+=(-DBOOST_HAS_PTHREADS -isystem "$SHIMS/tbb-serial")
fi

# Orca's own headers are included as system headers so -Wall reports only the bridge's warnings.
INCLUDES=(
  -isystem "$GEN"
  -isystem "$ORCA/src" -isystem "$ORCA/src/libslic3r"
  -isystem "$SHIMS/common" -isystem "$SHIMS/occt"
  -isystem "$ORCA/deps_src" -isystem "$ORCA/deps_src/libigl" -isystem "$ORCA/deps_src/libnest2d/include"
  -isystem "$ORCA/deps_src/clipper2/Clipper2Lib/include"
  -isystem "$DEPS/eigen-5.0.1" -isystem "$DEPS/cereal-1.3.0/include" -isystem "$DEPS/CGAL-5.6.3/include"
)
# Boost 1.84's CMake distribution keeps each library's headers in libs/<lib>/include.
for dir in "$DEPS"/boost-1.84.0/libs/*/include "$DEPS"/boost-1.84.0/libs/numeric/*/include; do
  INCLUDES+=(-isystem "$dir")
done

printf '%s\n' "${FLAGS[@]}" "${INCLUDES[@]}" | sed 's/\\/\//g' > "$GEN/flags.rsp"

FILES=("$@")
if [[ ${#FILES[@]} -eq 0 ]]; then
  FILES=(cli_config.cpp model_input.cpp toolpaths.cpp slice_job.cpp placement.cpp engine.cpp)
fi
status=0
for f in "${FILES[@]}"; do
  echo "== $VARIANT: $f"
  "$EMXX" "@$GEN/flags.rsp" "$HERE/$f" || status=1
done
exit $status
