# libslic3r and libslic3r_cgal as static libraries, built from ORCA_SRC with the settings of Orca's
# src/libslic3r/CMakeLists.txt, minus the desktop-only parts (see OrcaSources.cmake), plus the engine's
# shims and stubs.

include(OrcaSources)
include(OrcaSourcePatches)

set(LIBSLIC3R_DIR "${ORCA_SRC}/src/libslic3r")
set(LIBSLIC3R_GEN_DIR "${CMAKE_BINARY_DIR}/libslic3r")

# --- Generated files -------------------------------------------------------------------------------------------
# libslic3r_version.h exactly as Orca generates it. SoftFever_VERSION ends up in the G-code header
# ("; generated by OrcaSlicer 2.5.0-dev ..."), so it must come from the same version.inc. SLIC3R_BUILD_ID
# is left unset, as in Orca's CMake (only the SLA archive writer uses it).
include("${ORCA_SRC}/version.inc")
if (NOT DEFINED ORCA_CHECK_GCODE_PLACEHOLDERS)
    set(ORCA_CHECK_GCODE_PLACEHOLDERS "0")
endif ()
configure_file("${LIBSLIC3R_DIR}/libslic3r_version.h.in" "${LIBSLIC3R_GEN_DIR}/libslic3r_version.h" @ONLY)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ORCA_SRC}/version.inc")

orca_generate_drainhole_source("${LIBSLIC3R_GEN_DIR}/stubs/SLA/Hollowing.cpp")

# --- Sources ---------------------------------------------------------------------------------------------------
orca_libslic3r_sources(ORCA_LIBSLIC3R_ALL)
set(ORCA_LIBSLIC3R_KEPT ${ORCA_LIBSLIC3R_ALL})
foreach (excluded IN LISTS ORCA_LIBSLIC3R_EXCLUDED)
    list(FIND ORCA_LIBSLIC3R_ALL "${excluded}" index)
    if (index EQUAL -1)
        # Orca renamed or dropped the file: the exclusion (and its stub, if any) needs a look.
        message(WARNING "Excluded libslic3r source ${excluded} is no longer in Orca's source list.")
    endif ()
    list(REMOVE_ITEM ORCA_LIBSLIC3R_KEPT "${excluded}")
endforeach ()
list(TRANSFORM ORCA_LIBSLIC3R_KEPT PREPEND "${LIBSLIC3R_DIR}/")
# Sources with an out-of-tree fix (OrcaSourcePatches.cmake) are compiled from their patched copy.
foreach (entry IN LISTS ORCA_LIBSLIC3R_PATCHED)
    string(REPLACE "=" ";" entry "${entry}")
    list(GET entry 0 rel_path)
    list(GET entry 1 patched_copy)
    list(FIND ORCA_LIBSLIC3R_KEPT "${LIBSLIC3R_DIR}/${rel_path}" index)
    if (index EQUAL -1)
        message(FATAL_ERROR "Patched source ${rel_path} is not among the compiled libslic3r sources.")
    endif ()
    list(REMOVE_AT ORCA_LIBSLIC3R_KEPT ${index})
    list(INSERT ORCA_LIBSLIC3R_KEPT ${index} "${patched_copy}")
    message(STATUS "libslic3r: ${rel_path} is compiled from a patched copy (engine/PATCHES.md)")
endforeach ()
list(LENGTH ORCA_LIBSLIC3R_ALL n_all)
list(LENGTH ORCA_LIBSLIC3R_KEPT n_kept)
message(STATUS "libslic3r: ${n_kept} of Orca's ${n_all} sources (the rest are excluded or stubbed)")

# GUI-library source that libslic3r itself needs: FlushVolCalc.cpp calls RGB2HSV(), defined in
# src/slic3r/Utils/ColorSpaceConvert.cpp (the native CLI links the GUI library). It is compiled as it is,
# with a small wxColour stand-in for the wx header it includes (shims/wx).
set(ORCA_GUI_SOURCES_NEEDED "${ORCA_SRC}/src/slic3r/Utils/ColorSpaceConvert.cpp")
set_source_files_properties(${ORCA_GUI_SOURCES_NEEDED} PROPERTIES
    INCLUDE_DIRECTORIES "${ENGINE_DIR}/shims/wx"
    SKIP_PRECOMPILE_HEADERS ON)

set(ENGINE_STUB_SOURCES
    "${ENGINE_DIR}/stubs/Format/AssimpImport.cpp"
    "${ENGINE_DIR}/stubs/Format/DRC.cpp"
    "${ENGINE_DIR}/stubs/Format/STEP.cpp"
    "${ENGINE_DIR}/stubs/Format/svg.cpp"
    "${ENGINE_DIR}/stubs/Platform.cpp"
    "${ENGINE_DIR}/stubs/pthread_name.c"
    "${LIBSLIC3R_GEN_DIR}/stubs/SLA/Hollowing.cpp"
)

# --- Header shims ----------------------------------------------------------------------------------------------
# openssl/md5.h (Utils.hpp, included nearly everywhere) and the OCCT headers Format/STEP.hpp includes
# (Model.hpp includes STEP.hpp). Public: the bridge includes Model.hpp and Utils.hpp too.
add_library(engine_shims INTERFACE)
target_include_directories(engine_shims SYSTEM INTERFACE "${ENGINE_DIR}/shims/common" "${ENGINE_DIR}/shims/occt")

# --- libslic3r_cgal ----------------------------------------------------------------------------------------------
add_library(libslic3r_cgal STATIC
    "${LIBSLIC3R_DIR}/CutSurface.cpp"
    "${LIBSLIC3R_DIR}/IntersectionPoints.cpp"
    "${LIBSLIC3R_DIR}/MeshBoolean.cpp"
    "${LIBSLIC3R_DIR}/TryCatchSignal.cpp"
    "${LIBSLIC3R_DIR}/Triangulation.cpp"
)
target_include_directories(libslic3r_cgal PRIVATE "${LIBSLIC3R_GEN_DIR}")
# MeshBoolean.cpp -> libigl's copyleft/cgal/assign_scalar.h needs CGAL's Epeck_with_sqrt, which a GMP-free
# CGAL cannot provide; shims/cgal supplies a compile-only placeholder (see the header). It must be searched
# before CGAL's own include directory, hence BEFORE.
target_include_directories(libslic3r_cgal SYSTEM BEFORE PRIVATE "${ENGINE_DIR}/shims/cgal")

# As in Orca: CGAL's -frounding-math applies to libslic3r_cgal only, not to everything linking CGAL.
# (With CGAL_ALWAYS_ROUND_TO_NEAREST it changes nothing on wasm, but keep the options as Orca has them.)
get_target_property(_cgal_tgt CGAL::CGAL ALIASED_TARGET)
if (NOT TARGET ${_cgal_tgt})
    set(_cgal_tgt CGAL::CGAL)
endif ()
get_target_property(_opts ${_cgal_tgt} INTERFACE_COMPILE_OPTIONS)
if (_opts)
    set(_opts_bad "${_opts}")
    set(_opts_good "${_opts}")
    list(FILTER _opts_bad INCLUDE REGEX frounding-math)
    list(FILTER _opts_good EXCLUDE REGEX frounding-math)
    set_target_properties(${_cgal_tgt} PROPERTIES INTERFACE_COMPILE_OPTIONS "${_opts_good}")
    target_compile_options(libslic3r_cgal PRIVATE "${_opts_bad}")
endif ()
# Orca's list, plus the TBB headers (Point.hpp includes oneapi/tbb/scalable_allocator.h; natively they sit
# in the same prefix as Boost) and the shims (Utils.hpp -> openssl/md5.h).
target_link_libraries(libslic3r_cgal PRIVATE ${_cgal_tgt} admesh libigl mcut boost_libs TBB::tbb engine_shims)

# --- libslic3r -----------------------------------------------------------------------------------------------------
add_library(libslic3r STATIC ${ORCA_LIBSLIC3R_KEPT} ${ORCA_GUI_SOURCES_NEEDED} ${ENGINE_STUB_SOURCES})

target_compile_definitions(libslic3r PUBLIC USE_TBB TBB_USE_CAPTURED_EXCEPTION=0)
target_compile_features(libslic3r PUBLIC cxx_std_17)   # its headers need C++17; consumers inherit it
target_include_directories(libslic3r
    PRIVATE "${LIBSLIC3R_DIR}" "${LIBSLIC3R_DIR}/TextureToColor"
    PUBLIC "${LIBSLIC3R_GEN_DIR}")
target_include_directories(libslic3r SYSTEM PUBLIC ${EXPAT_INCLUDE_DIRS})
# Orca puts src/ on every target's include path (a directory property); consumers of the library (the
# bridge, tests) get it from the target here as well, for <libslic3r/...> includes.
target_include_directories(libslic3r SYSTEM PUBLIC "${ORCA_SRC}/src")

# Orca's link list without the desktop-only libraries (opencv_world, assimp, OCCT, draco, OpenSSL,
# freetype/fontconfig, dl).
target_link_libraries(libslic3r
    PUBLIC
        Eigen3::Eigen
        admesh
        libigl
        libnest2d
        miniz
        engine_shims
    PRIVATE
        ${EXPAT_LIBRARIES}
        boost_libs
        cereal::cereal
        clipper
        Clipper2
        glu-libtess
        JPEG::JPEG
        libslic3r_cgal
        mcut
        noise::noise
        PNG::PNG
        qhull
        qoi
        semver
        TBB::tbb
        TBB::tbbmalloc
        ZLIB::ZLIB
)

# Orca builds libslic3r with pchheader.hpp as a precompiled header (SLIC3R_PCH, on in its Linux build),
# which also force-includes it into every source. Doing the same keeps the translation units identical to
# Orca's and saves a lot of compile time.
if (ENGINE_PCH)
    target_precompile_headers(libslic3r PRIVATE "${LIBSLIC3R_DIR}/pchheader.hpp")
    target_compile_options(libslic3r PRIVATE "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-Xclang -fno-pch-timestamp>")
    set_source_files_properties("${ENGINE_DIR}/stubs/pthread_name.c" PROPERTIES SKIP_PRECOMPILE_HEADERS ON)
endif ()
