# Out-of-tree fixes to Orca sources, for defects that only show on wasm32 and cannot be worked around
# with a shim or a stub. The Orca checkout is never modified: a patched copy of the file is generated in
# the build tree and compiled instead of the original. Every patch is an exact text replacement that
# must match exactly once, so a change in Orca makes the configure step fail instead of silently
# compiling something else. Each one is listed, with its reason and how it was verified, in
# engine/PATCHES.md; they are candidates for upstreaming to the fork as portable fixes.

# orca_patch_source(<path relative to src/libslic3r> <out_var>
#                   FIND <text> REPLACE <text> [FIND <text> REPLACE <text> ...])
# Writes the patched copy and sets <out_var> to its path. The copy starts with a #line directive, so
# diagnostics and __FILE__ still name the original file, and it gets the original's directory on its
# include path, so its quoted includes resolve as before.
function(orca_patch_source rel_path out_var)
    set(orca_file "${ORCA_SRC}/src/libslic3r/${rel_path}")
    set(out_file "${CMAKE_BINARY_DIR}/libslic3r/patched/${rel_path}")
    file(READ "${orca_file}" text)

    # The pairs are read through ARGV<n>: the texts contain ';', which ${ARGN} would split.
    math(EXPR n_pairs "(${ARGC} - 2) / 4")
    math(EXPR rest "(${ARGC} - 2) % 4")
    if (n_pairs EQUAL 0 OR NOT rest EQUAL 0)
        message(FATAL_ERROR "orca_patch_source(${rel_path}): expected FIND <text> REPLACE <text> pairs.")
    endif ()
    math(EXPR last_pair "${n_pairs} - 1")
    foreach (pair RANGE ${last_pair})
        math(EXPR i "2 + 4 * ${pair}")
        math(EXPR i_find "${i} + 1")
        math(EXPR i_kw_replace "${i} + 2")
        math(EXPR i_replace "${i} + 3")
        if (NOT "${ARGV${i}}" STREQUAL "FIND" OR NOT "${ARGV${i_kw_replace}}" STREQUAL "REPLACE")
            message(FATAL_ERROR "orca_patch_source(${rel_path}): expected FIND <text> REPLACE <text> pairs.")
        endif ()
        set(find "${ARGV${i_find}}")
        set(replace "${ARGV${i_replace}}")
        # Exactly one occurrence, or the patch no longer describes the file.
        string(FIND "${text}" "${find}" first)
        string(FIND "${text}" "${find}" last REVERSE)
        if (first EQUAL -1 OR NOT first EQUAL last)
            message(FATAL_ERROR "Patch for ${orca_file} no longer applies: the text\n  ${find}\nmust occur "
                                "exactly once. Orca changed; review the patch in engine/cmake/OrcaSourcePatches.cmake "
                                "and engine/PATCHES.md.")
        endif ()
        string(REPLACE "${find}" "${replace}" text "${text}")
    endforeach ()

    file(WRITE "${out_file}.tmp"
        "// Patched copy of ${orca_file}, generated by engine/cmake/OrcaSourcePatches.cmake.\n"
        "// Do not edit; see engine/PATCHES.md.\n"
        "#line 1 \"${orca_file}\"\n"
        "${text}")
    # Rewrite only on change, so a re-configure does not force a rebuild.
    file(COPY_FILE "${out_file}.tmp" "${out_file}" ONLY_IF_DIFFERENT)
    file(REMOVE "${out_file}.tmp")
    get_filename_component(orca_dir "${orca_file}" DIRECTORY)
    set_source_files_properties("${out_file}" PROPERTIES INCLUDE_DIRECTORIES "${orca_dir}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${orca_file}")
    set(${out_var} "${out_file}" PARENT_SCOPE)
endfunction()

# --- The patches ------------------------------------------------------------------------------------------------
# Each entry: the Orca file (relative to src/libslic3r) and its replacements. ORCA_LIBSLIC3R_PATCHED maps
# the original to the copy for Libslic3r.cmake.
set(ORCA_LIBSLIC3R_PATCHED)

# 1. Arachne/SkeletalTrapezoidation.cpp, SkeletalTrapezoidation::interpolate(): the reverse loop starts at
#    `left.toolpath_locations.size() - 1` assigned to a coord_t (int64). With an empty vector that is
#    SIZE_MAX, which becomes -1 in an int64 only where size_t is 64-bit. On wasm32 it becomes 4294967295,
#    the loop runs and reads toolpath_locations[4294967295]: "memory access out of bounds" while slicing
#    a Benchy with Arachne walls. Converting before subtracting gives -1 on every target (no change for
#    64-bit builds).
orca_patch_source(Arachne/SkeletalTrapezoidation.cpp patched
    FIND    "for (next_inset_idx = left.toolpath_locations.size() - 1; next_inset_idx >= 0; next_inset_idx--)"
    REPLACE "for (next_inset_idx = coord_t(left.toolpath_locations.size()) - 1; next_inset_idx >= 0; next_inset_idx--)")
list(APPEND ORCA_LIBSLIC3R_PATCHED "Arachne/SkeletalTrapezoidation.cpp=${patched}")
